### ISSUE TITLE
java.lang.UnsatisfiedLinkError: jline ...dll: A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by rustyx** [jdillon/mvnsh#7]
After running 123 `mvn install:install-file` commands I always get getting this error

```
java.lang.UnsatisfiedLinkError: C:\TEMP\jline\jline6839375240983950276.dll: A dynamic link library (DLL) initialization routine failed
java.lang.UnsatisfiedLinkError: C:\TEMP\jline\jline6426628542205626973.dll: A dynamic link library (DLL) initialization routine failed
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at jline.internal.NativeLibrary.load(NativeLibrary.java:107)
        at jline.WindowsTerminal.init(WindowsTerminal.java:88)
        at jline.TerminalSupport.reset(TerminalSupport.java:53)
        at org.sonatype.gshell.console.Console.run(Console.java:148)
        at org.sonatype.gshell.shell.ShellImpl.run(ShellImpl.java:292)
        at org.sonatype.gshell.MainSupport.boot(MainSupport.java:286)
        at org.sonatype.maven.shell.Main.main(Main.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonatype.maven.shell.launcher.Launcher.launch(Launcher.java:75)
        at org.sonatype.maven.shell.launcher.Launcher.run(Launcher.java:48)
        at org.sonatype.maven.shell.launcher.Launcher.main(Launcher.java:39)

WARNING: Abnormal JVM shutdown detected
```

Windows 7 x64
mvnsh 1.1.0
mvn 3.0.5

**Comment by rustyx** [comment]
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by rustyx** [comment]
Correction: this happens for me after **any 122 mvn invocations**.

Example: get this file: [mvnsh-test.txt](http://rustyx.org/temp/mvnsh-test.txt) and run it:

`mvnsh.bat -c "source mvnsh-test.txt"`

**Comment by jdillon** [comment]
mvnsh and gshell now use jline3 which is quite a bit different; though i'm not sure how this would have been a bug with mvnsh or not.  for now gonna close; if you happen to have problems running 123 mvn commands in the latest shapshot please re-open.
